[tool.poetry]
name = "barcode-verification"
version = "0.1.0"
description = "Daejin barcode verification program"
authors = ["David Cho <csi00700@gmail.com>"]
license = "MIT"
readme = "README.md"
keywords = ["barcode", "verification"]

[tool.poetry.dependencies]
requests = { version = ">=2.31.0" }

# [tool.poetry.dev-dependencies]
# pytest = { version = ">=7.4.0" }
# pytest-cov = { version = ">=4.1.0" }
# pytest-mock = { version = ">=3.11.1" }
# black = { version = ">=23.3.0" }
# isort = { version = ">=5.12.0" }
# flake8 = { version = ">=6.0.0" }
# mypy = { version = ">=1.3.0" }
# pre-commit = { version = ">=3.3.3" }

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 88
target-version = ['py39', 'py310', 'py311', 'py312']
include = '\.pyi?$'

[tool.isort]
profile = "black"
multi_line_output = 3
line_length = 88

[tool.mypy]
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true

[tool.pytest.ini_options]
addopts = "-v --tb=short"
testpaths = ["tests"]
python_files = ["test_*.py"]
python_classes = ["Test*"]
python_functions = ["test_*"]
